# Generated by Django 5.1.6 on 2025-07-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
