# Generated by Django 5.1.6 on 2025-07-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0005_wishitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishitem',
            name='date_added',
        ),
    ]
